export const EVENTS = {
  DOCTOR_CREATED: 'doctor.created',
  DOCTOR_UPDATED: 'doctor.updated',
  DOCTOR_DELETED: 'doctor.deleted',
  INSTITUTION_CREATED: 'institution.created',
  INSTITUTION_UPDATED: 'institution.updated',
  JOB_CREATED: 'job.created',
  JOB_UPDATED: 'job.updated',
  CONNECTION_CREATED: 'connection.created',
  CONNECTION_REMOVED: 'connection.removed',
  POST_CREATED: 'post.created',
  POST_LIKED: 'post.liked',
  POST_COMMENTED: 'post.commented',
  PATIENT_CREATED: 'patient.created',
  PATIENT_UPDATED: 'patient.updated',
  WORKPLACE_CREATED: 'workplace.created',
  WORKPLACE_UPDATED: 'workplace.updated',
  APPOINTMENT_CREATED: 'appointment.created',
  APPOINTMENT_CANCELLED: 'appointment.cancelled',
};
